# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ['--line-length=120']

#  - repo: https://github.com/adrienverge/yamllint
#    rev: v1.33.0
#    hooks:
#      - id: yamllint

#  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
#    rev: v0.0.9  # Use the ref you want to point at
#    hooks:
#    -   id: add-msg-issue-prefix

  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.3
    hooks:
      - id: auto-smart-commit

  - repo: local
    hooks:
    - id: check-branch-name
      name: Check branch name
      entry: python
      args: ["script/pre-commit/validate_branch_name.py"]
      language: system
      types: [python]
#      args:
#      - ^main$
#      - ^release$
#      - ^(feature|fix|hotfix)\/SK-\d*-[a-zA-Z0-9_-]+$
#      exclude: ^release\/.*$
      pass_filenames: false
